### ISSUE TITLE
Type error reported by `@typescript-eslint/no-unsafe-return`

### ISSUE THREAD

**Issue by karlhorky** [syntax-tree/hast-util-to-jsx-runtime#10]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=issues) and [discussions](https://github.com/orgs/syntax-tree/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

hast-util-to-jsx-runtime@2.3.2

### Steps to reproduce

1. Configure [`@typescript-eslint/no-unsafe-return`](https://typescript-eslint.io/rules/no-unsafe-return/) rule in some Node.js or Next.js project (eg. Next.js App Router project)
2. Add [Shiki example code for `hast-util-to-jsx-runtime`](https://shiki.style/packages/next#custom-components) in `components/CodeBlock.tsx`
3. 💥 Observe "Unsafe return of a value of type error" error with return value

[Reproduction (`typescript-eslint` Playground)](https://typescript-eslint.io/play/#ts=5.7.2&fileType=.tsx&code=JYWwDg9gTgLgBAbzjCApAzgDwEoFcB2MoApnAL5wBmUEIcA5ABYCG6MAtLkQDbsrsArLOygEiIYvQDcAKFCRYiOADEozAOYTCAGmQBPMKVQBlABrkqNOvSjFmAYxjS54aPCRDMuz%2BgvVaDLYOMAD0niJiJM7ybkr2EAAmxAAqEAASrPAU-tbojMAA1sDOMsSYCvCsevj2VASOwBD4cADCicQAQtwQ9gUAFACUiDJwcPH4bHAQXHAAvHDMAO7MwPDxSakZbH304%2BgQ3MQAdN3qfQBEacTc3XAA6tDcCecD9LoII6Nw3Mz46gBcDBg6Den1GMEYxAkgPoCWYUAK7DA3FwIO0nzIA1kn1sMFwUGaKAwOEiEj60xg7zBKjUmmIOmpnnRXzgPmZX3irnw9OBgI%2BLNGIRCcD00ygY1RKDoAAMwLZpXBrlCedTRnLiIC%2BnKIGB0ENZgA%2BOAAHnVcDhMGY7Hskto1vaACNur1EEc3drdRQQgb2aMyOzMbIyDIgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolrRE%2BWNCbooiaNA7RI4MAF8QKoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUjxYAEw7oASuhKxUbAsQpQW89C3QAPPJEk0oshRh2Qi%2BosdNSAviBdA&tokens=false)

```
Unsafe return of a value of type error. 12:3 - 20:6
```

![Screenshot 2024-12-06 at 15 11 13](https://github.com/user-attachments/assets/b4b07630-9b27-471e-a401-8314d45bd1ff)

Using a `as JSX.element` type assertion on the return value of `toJsxRuntime()` is a workaround for the issue:

![Screenshot 2024-12-06 at 15 11 26](https://github.com/user-attachments/assets/7a159c0f-5176-434a-991d-f8aed5ba89dd)

### Actual behavior

Error with a "type error". The type error is not observable.

### Expected behavior

No error

### Runtime

node@22.11.0

### Package manager

yarn@1.22.22

### Operating system

macOS Sequoia 15.1.1

### Build and bundle tools

other (please specify in steps to reproduce)

**Comment by karlhorky** [comment]
Maybe related to #6 ?

**Comment by remcohaszing** [comment]
This is an XY-problem. Your linter complains. The real problem is that there is a type error in `hast-util-to-jsx-runtime` when using it with modern JSX frameworks, which now include React 19. You’re just suppressing the type error.

This is indeed what I tried to fix in #6. As a workaround you can define the global JSX namespace yourself, do a type cast, or add an `eslint-disable` comment. I recommend type-casting to `ReactElement`.

**Comment by karlhorky** [comment]
To be clear, that's just a workaround though - does `hast-util-to-jsx-runtime` intend to fix this issue too?

I can't observe the actual TS type error in my editor / on the command line via `tsc` weirdly enough, only `typescript-eslint` can see it.

**Comment by remcohaszing** [comment]
The `JSX` namespace is a special internal type to tell TypeScript how JSX works. They are obvervable to React users, but they’re not really intended for public use. In React, `JSX.Element` is an alias of `ReactElement.

JSX frameworks used to define the `JSX` namespace globally. This was really convenient for types that work with JSX in a generic manner, such as `hast-util-to-jsx` and `@types/mdx`. But over recent years all major JSX frameworks have moved away from the global `JSX` namespace, React being the last one with React 19.

IMO we should not rely on the global JSX namespace anymore at all, but the team is in disagreement on this. Also even if we do, the problem is hard to resolve. If we can’t rely on the `JSX` namespace, a lot of types internally become `any`/`unknown`.

**Comment by wooorm** [comment]
This project depends on JSX, which is why it uses the quite useful `JSX` types. Type them and it works. Or don’t, then there are no types. I would really appreciate it if people talk to TS/React folks who want to go without these useful types. There are several other places where this can be discussed, and this ESLint rule isn’t it.

**Comment by karlhorky** [comment]
Thanks for the background!

> This project depends on JSX, which is why it uses the quite useful `JSX` types. Type them and it works.

@wooorm I'm guessing that you mean ae638ba52762906fe094d74f82ba835ce23a2621, the recommendation in the Use section of the readme to use the following code:

```ts
import type {JSX as Jsx} from 'react/jsx-runtime'

declare global {
  namespace JSX {
    type ElementClass = Jsx.ElementClass
    type Element = Jsx.Element
    type IntrinsicElements = Jsx.IntrinsicElements
  }
}
```

![Screenshot 2024-12-06 at 19 01 13](https://github.com/user-attachments/assets/3a78b695-6e83-4f10-a7bd-08cfd0b5b000)

It seems like it's kind of ok, but it's a lot of code for common use cases, and the error DX is not great (finding the error first of all, and then finding out that it's not a bug but a separate setup requirement - to paste code in some file). 

Since there is [the widespread removal of the global `JSX` interface](https://github.com/syntax-tree/hast-util-to-jsx-runtime/pull/6#issuecomment-2004318696), it does feel like the generic option would be slightly better - I'm guessing it would lead to code like this?

```ts
import { type JSX } from 'react';

toJsxRuntime<JSX>(...)
```

I'm not sure whether this was considered somewhere (maybe already in #6, if I didn't understand completely yet), but would it be possible to retrieve the type from the passed `jsx` function somehow instead?

So that no code would need to change, and the type is somehow retrieved from the function?

```ts
import { toJsxRuntime } from 'hast-util-to-jsx-runtime';
import { Fragment } from 'react';
import { jsx, jsxs } from 'react/jsx-runtime';

toJsxRuntime(out, {
  Fragment,
  jsx, // Type retrieved from this `jsx` function
  jsxs,
});
```
